### ISSUE TITLE
Grafana Operator in smaug crashlooping

### ISSUE THREAD

**Issue by HumairAK** [operate-first/apps#2132] opened 2022-07-12 17:00 UTC
https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/opf-monitoring/pods/grafana-operator-controller-manager-7d559645db-g4sw6

As a consequence dashboards are not being added

**Comment by harshad16** [comment] 2022-07-12 17:02
![Screenshot from 2022-07-12 13-02-17](https://user-images.githubusercontent.com/14028058/178550671-c6246eb8-e4b1-4981-b12e-f24661acd591.png)

**Comment by harshad16** [comment] 2022-07-12 17:10
There doesnt seems to be any breaking changes known
https://github.com/grafana-operator/grafana-operator/releases/tag/v4.5.0

**Comment by harshad16** [comment] 2022-07-13 03:19
![Screenshot from 2022-07-12 23-12-34](https://user-images.githubusercontent.com/14028058/178642867-6216b9e8-7510-42dd-bafa-15b8c334c7bb.png)

As grafana dashboard was causing the hindrance to grafana operator update.
The removal of grafana dashboard has helped succesfful update of the grafana operator
we have re-synced the dashboard, the operator is stable now.

This has solved the crash looping.
Technically this issue is done. 
However, the grafana dashboard are unable to be auto-updated.
Not a breaking error, so closing this issue as complete.

**Comment by harshad16** [comment] 2022-07-15 13:42
Reopening as this is still happening. Reference: https://github.com/operate-first/support/issues/609

**Comment by harshad16** [comment] 2022-07-19 17:02
On further investigation found the issue is happening regarding the dashboard sync with grafana.
The grafana operator is unable access the api folder from grafana.
`ERROR failed to get or create namespace folder for dashboard {"folder": "thoth-station", "dashboard": "pulp-metrics", "error": "error creating folder, expected status 200 but got 409"}`
`ERROR failed to get or create namespace folder for dashboard	{"folder": "Operate-First", "dashboard": "", "error": "Get \"http://admin:***@grafana-service.opf-monitoring.svc.cluster.local:3000/api/folders\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

A similar issue was observed in the earlier version of grafana operator:
https://github.com/grafana-operator/grafana-operator/issues/496

Currently, there was issue listed upstream with regards to the dashboard, however a different error type
https://github.com/grafana-operator/grafana-operator/issues/789

Going forward to checking with grafana team.

**Comment by harshad16** [comment] 2022-07-19 18:28
Operator error logs for reference:
[grafana-operator-controller-manager-7d559645db-6p79p-manager (1).log](https://github.com/operate-first/apps/files/9143727/grafana-operator-controller-manager-7d559645db-6p79p-manager.1.log)
[grafana-operator-controller-manager-7d559645db-6p79p-manager.log](https://github.com/operate-
first/apps/files/9143728/grafana-operator-controller-manager-7d559645db-6p79p-manager.log)
[grafana-operator-controller-manager-7d559645db-54brj-manager (1).log](https://github.com/operate-first/apps/files/9143729/grafana-operator-controller-manager-7d559645db-54brj-manager.1.log)
[grafana-operator-controller-manager-7d559645db-54brj-manager.log](https://github.com/operate-first/apps/files/9143730/grafana-operator-controller-manager-7d559645db-54brj-manager.log)

**Comment by harshad16** [comment] 2022-07-25 17:20
With the release of Operator [v.4.5.1 ](https://github.com/grafana-operator/grafana-operator/releases/tag/v4.5.1)
The system is now stable.

**Closed by harshad16** 2022-07-25 17:20 UTC
Labels: area/service/grafana, cluster/smaug
