### ISSUE TITLE
OSC CL2 cluster is running trino:362

### ISSUE THREAD

**Issue by erikerlandson** [operate-first/apps#1842] opened 2022-04-01 14:29 UTC
It's supposed to be running >= trino:372, preferably 373
cc @MichaelTiemannOSC @caldeirav @rimolive

**Comment by erikerlandson** [comment] 2022-04-01 14:42
So we need a 373 image build if @rimolive can do that

**Comment by HumairAK** [comment] 2022-04-01 14:46
to upgrade to 373, pr looks similar to: https://github.com/operate-first/odh-manifests/pull/11
followed by an odh operator restart (in the openshift-operators namespace), then ensuring coordinator/workerpods restart successfully (should happen automatically after rebooting odh operator)

**Comment by HumairAK** [comment] 2022-04-11 13:08
seems duplicate of: https://github.com/operate-first/apps/issues/1843

**Closed by HumairAK** 2022-04-11 13:08 UTC
